pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                dir('cucumber-jmeter-framework') {
                    bat 'mvn clean test'
                }
            }
        }

    }
}
